export const transactionHistoryList = [
    {
        "id": 456436455,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here.",
        "date": "01/01/19",
        "time": "09.00",
        "balance": "129.45",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 576476457,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here.",
        "date": "01/01/19",
        "time": "10.00",
        "balance": "45.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 555666545,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here. Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here.",
        "date": "04/01/19",
        "time": "12.34",
        "balance": "110.56",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 513266676,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "01/02/19",
        "time": "12.35",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647773,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647773,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647775,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647788,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647871,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647879,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647876,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647872,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647893,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647894,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647895,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
    {
        "id": 985647896,
        "description": "Description continues here and here and here and here and here. Short Description continues here and here and here and here and here. Short Description continues here and here and here and here ",
        "date": "12/21/2019",
        "time": "13.23",
        "balance": "39.99",
        "pdfURL": "http://www.africau.edu/images/default/sample.pdf",
    },
];