export const notificationResponse = {
    "code": 0,
    "message": "0",
    "data": {
        "recent": [
            {
                "id": 33509,
                "title": "The Resident S2 E2 - The Prince & the Pauper",
                "image": "https://img.hotstar.com/image/upload/f_auto,t_hcdl/sources/r1/cms/prod/649/40649-h",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Drama",
                ],
                "position": 3,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:42:00",
                "genre": [
                    "Drama",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Hotstar",
                "providerContentId": "1770018882",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "Bell grows frustrated when Marshall Winthrop, Conrad’s dad and new chairman of the board, requests Conrad’s input in his discussions about the hospital’s expenses.",
                "pageType": "",
            },
            {
                "id": 34066,
                "title": "The Flash S5 E10 - The Flash & The Furious",
                "image": "https://img.hotstar.com/image/upload/f_auto,t_hcdl/sources/r1/cms/prod/717/230717-h",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Action",
                ],
                "position": 4,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:42:22",
                "genre": [
                    "Action",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Hotstar",
                "providerContentId": "1224071687",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "Caitlin & Cisco discuss creating a meta-human cure.requests Conrad’s input in his discussions about the hospital’s expenses.",
                "pageType": "",
            },
            {
                "id": 152320,
                "title": "The Skinner Boys S2 E11 - The Yeti & The Stonemaker",
                "image": "https://m.media-amazon.com/images/S/sgp-catalog-images/region_GLOBAL/zdfent-27100031_IN-Full-Image_GalleryCover-hi-IN-1487892178829.jpg",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Kids",
                ],
                "position": 5,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:23:00",
                "genre": [
                    "Kids",
                ],
                "language": [
                    "",
                ],
                "allowedOnBrowsers": true,
                "provider": "Prime",
                "providerContentId": "amzn1.dv.gti.7cacccbd-898b-3e1a-047d-a61dfe2cfe4c",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "When a powerful artefact, the Stone Maker, is used to bring a stone yeti warrior to life, Can Henry and Edward stall the attack until Charles and Tara return with the brother?",
                "pageType": "",
            },
            {
                "id": 121314,
                "title": "The Toothbrush Family S1 E15 - The Laundry Room / The Special Award / The Belle of the Ball / Super Heroes",
                "image": "https://m.media-amazon.com/images/S/sgp-catalog-images/region_GLOBAL/ylkmo-E44K1AWS411-Full-Image_GalleryCover-en-US-1562946431872.png",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Kids",
                ],
                "position": 6,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:18:00",
                "genre": [
                    "Kids",
                ],
                "language": [
                    "",
                ],
                "allowedOnBrowsers": true,
                "provider": "Prime",
                "providerContentId": "amzn1.dv.gti.74afd2a8-9bb9-1d76-a689-5a4155376e3f",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "When Flash admits he has had a bad dream about the mysterious laundry room robot, Susie Sponge helps Flash out. / Being nominated for the \"Toothbrush Tube of the Month\" should be Flash's greatest moment but it becomes his greatest nightmare! / Countess De Comb longs for the days of her youth when she was the \"Belle of the Ball\". / Flash becomes a Super Hero!",
                "pageType": "",
            },
            {
                "id": 151217,
                "title": "Classic Tales S1 E12 - The Town Mouse and the Country Mouse / The Brave Little Parrot / The Three Billy Goats Gruff / The Frog Prince / The Wolf and the Dog",
                "image": "https://m.media-amazon.com/images/S/sgp-catalog-images/region_GLOBAL/ylkmo-J6F9H32FEMW-Full-Image_GalleryCover-en-US-1565283268063.jpg",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Animation, Adult Interest",
                    "Kids",
                ],
                "position": 7,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:24:00",
                "genre": [
                    "Animation, Adult Interest",
                    "Kids",
                ],
                "language": [
                    "",
                ],
                "allowedOnBrowsers": true,
                "provider": "Prime",
                "providerContentId": "amzn1.dv.gti.06afed50-88e2-3874-4704-de7664a5f8b9",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "A humble mouse visits his cousin's rich home and discovers a realisation. / The story of the heroic actions of a very brave, young parrot. / Three goat brothers must get past a troll which guards a bridge. / A princess discovers there's more to an ugly frog than she'd first thought. / A hungry, cold wolf finds that the warm, comfortable life led by a dog isn't as good as it first appeared.",
                "pageType": "",
            },
            {
                "id": 149312,
                "title": "Classic Tales S1 E11 - The Little Mermaid / The Donkey and the Bell / The Elephant's Child / The Old Woman and her Pig / The Hare and the Tortoise",
                "image": "https://m.media-amazon.com/images/S/sgp-catalog-images/region_GLOBAL/ylkmo-J6F9H32FEMW-Full-Image_GalleryCover-en-US-1565283268063.jpg",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Animation, Adult Interest",
                    "Kids",
                ],
                "position": 8,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:24:00",
                "genre": [
                    "Animation, Adult Interest",
                    "Kids",
                ],
                "language": [
                    "",
                ],
                "allowedOnBrowsers": true,
                "provider": "Prime",
                "providerContentId": "amzn1.dv.gti.dcafed50-fc40-435d-7699-64d54f74b16f",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "The youngest daughter of the Sea King achieves her desire to join the human world. / After a humble donkey is given a beautiful bell to wear and he becomes too proud for his own good. / A young elephant's curiosity gets him into a sticky situation. / After a woman buys a pig at the market, she's dismayed when it refuses to walk home with her. / A tortoise challenges the hare to a race.",
                "pageType": "",
            },
            {
                "id": 126282,
                "title": "Molang S1 E7 - The Party /  The Bicycle",
                "image": "https://m.media-amazon.com/images/S/sgp-catalog-images/region_GLOBAL/klq49-E8A1PDVDXC9-Full-Image_GalleryCover-en-US-1572344045465.png",
                "imageUrlDongle": "",
                "contentType": "TV_SHOWS",
                "contentShowType": "VOD_TV_SHOWS",
                "subTitles": [
                    "Kids",
                ],
                "position": 9,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "duration": "00:07:00",
                "genre": [
                    "Kids",
                ],
                "language": [
                    "",
                ],
                "allowedOnBrowsers": true,
                "provider": "Prime",
                "providerContentId": "amzn1.dv.gti.e4b0e326-0480-e954-95c3-f9df9fdbde46",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "Molang is an affectionate, humorous look at the relationship between an eccentric, joyful, and enthusiastic rabbit, and a shy, discreet, and emotional little chick. The series explores Molang and Piu Piu's everyday life with warmth and humor. From camel rides to fishing trips with friends, ever single moment is full of happiness.",
                "pageType": "",
            },
        ],
        "earlier": [
            {
                "id": 1268,
                "title": "The Matchmaker",
                "image": "https://content7.hungama.com/short%20films/display%20image/1280x800%20jpeg/3637306555.jpg",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Romance",
                ],
                "position": 1,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "genre": [
                    "Romance",
                ],
                "language": [
                    "Hindi",
                ],
                "allowedOnBrowsers": true,
                "provider": "Hungama",
                "providerContentId": "32640651",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "Karan (Akash Dhar) has a normal life with his wife (Shruti Marathe) & son, but he realises that he is not happy as husband. Karan decides to live his fantasy through a machine which introduces him to a woman of his dreams, Amaira (Shezali Sharma). This romantic Hindi movie takes a twist when reality of his infidelity hits Karan..... Film also stars Gaurav Ghatnekar.",
                "pageType": "",
            },
            {
                "id": 1270,
                "title": "The Windows",
                "image": "https://content4.hungama.com/short%20films/display%20image/1280x800%20jpeg/3637306552.jpg",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Motivational",
                ],
                "position": 2,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "genre": [
                    "Motivational",
                ],
                "language": [
                    "Marathi",
                ],
                "allowedOnBrowsers": true,
                "provider": "Hungama",
                "providerContentId": "32640656",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "The story outlines a man who is very aware about his environment, critical about daily life, people and the pollution caused by them. But one day it changes..... This Marathi short film is subtitled in English was Official selection in Goa Enviromental Film Festival.",
                "pageType": "",
            },
            {
                "id": 64177,
                "title": "The Gallant Captain",
                "image": "http://tank.tskytech.com/jumpstart/Temp/cdn/HLS/VOD/imageContent-8277-jzmhnllc-v1/imageContent-8277-jzmhnllc-m1.jpg",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Adventure",
                ],
                "position": 6,
                "contractName": "FREE",
                "entitlements": [
                    "2392",
                ],
                "duration": "00:07:29",
                "genre": [
                    "Adventure",
                ],
                "language": [
                    "Hindi",
                    "Tamil",
                    "Telugu",
                    "Malayalam",
                ],
                "allowedOnBrowsers": true,
                "provider": "Tatasky",
                "providerContentId": "PKTS2018092710059181",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "After discovering a box of his father's memories, Will, a young fanciful boy, embarks on a nautical voyage with his faithful cat in an attempt to retrace his missing father's last route. Cast: Toby Pearce; Dir: Graeme Base, Katrina Mathers; Animation; Australia 2013.",
                "pageType": "",
            },
            {
                "id": 187,
                "title": "Above The Gravity",
                "image": "http://tank.tskytech.com/Jumpstart/Temp/cdn/HLS/VOD/imageContent-1296-j4nzoqls-v4/imageContent-1296-j4nzoqls-m4.png",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Entertainment",
                ],
                "position": 7,
                "contractName": "FREE",
                "entitlements": [
                    "217",
                ],
                "duration": "00:03:43",
                "genre": [
                    "Entertainment",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Tatasky",
                "providerContentId": "PKTS2016092910000131",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "French pilot Florent Graffouillere puts on a one man air show as he tricks through the skies via plane and paraglider.",
                "pageType": "",
            },
            {
                "id": 231,
                "title": "Dancing With The Cars",
                "image": "http://tank.tskytech.com/Jumpstart/Temp/cdn/HLS/VOD/imageContent-1507-j4p69ao8-v1/imageContent-1507-j4p69ao8-m1.png",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Entertainment",
                ],
                "position": 9,
                "contractName": "FREE",
                "entitlements": [
                    "263",
                ],
                "duration": "00:01:54",
                "genre": [
                    "Entertainment",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Tatasky",
                "providerContentId": "PKTS2016100510000125",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "Amy Marie Gaertner looks like a giant as she dances with 189 remote controlled cars.",
                "pageType": "",
            },
            {
                "id": 1271,
                "title": "The Souls Of India",
                "image": "https://content1.hungama.com/short%20films/display%20image/1280x800%20jpeg/3637306551.jpg",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Drama",
                ],
                "position": 10,
                "contractName": "FREE",
                "entitlements": [
                    "",
                ],
                "genre": [
                    "Drama",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Hungama",
                "providerContentId": "32640655",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "This film is about Indian values, culture and humanity. In 4000 BC, Abhimanyu tells the villagers a story about sacrifice of the family of his Guru (Teacher) when there was a famine in the village..",
                "pageType": "",
            },
            {
                "id": 6885,
                "title": "Motherhood",
                "image": "http://tank.tskytech.com/jumpstart/Temp/cdn/HLS/VOD/imageContent-6458-jlz1kmjs-v1/imageContent-6458-jlz1kmjs-m1.png",
                "imageUrlDongle": "",
                "contentType": "WEB_SHORTS",
                "contentShowType": "VOD_WEB_SHORTS",
                "subTitles": [
                    "Documentary",
                ],
                "position": 11,
                "contractName": "FREE",
                "entitlements": [
                    "1830",
                ],
                "duration": "00:42:52",
                "genre": [
                    "Documentary",
                ],
                "language": [
                    "English",
                ],
                "allowedOnBrowsers": true,
                "provider": "Tatasky",
                "providerContentId": "PKTS2017061310043106",
                "blackOut": false,
                "categoryType": "DEFAULT",
                "rentalPrice": "0",
                "summary": "This series follows four or five placer mining crews as they search for PKTS2017061310043106 over the four-month Yukon mining season. PKTS2017061310043106 mining season begins in Dawson City, Yukon, and the countdown to winter is on. With the price of PKTS2017061310043106 hovering at record-breaking levels, a modern day PKTS2017061310043106 rush is underway. Rookie \"Big Al\" has qualms when his excavator \"Big Girl\" breaks down and meets with disaster. In Moose Creek, bosom buddies Ken and Guillaume cannot even get their sluicer machine \"The Beast\" to start. Meanwhile, Bernie struggles with an inexperienced crew- his young sons while he teaches them how to be miners. Due to the unexpected mechanical breakdowns, could the entire mining season be a bust? Cast: Ken Foy, Al Mc Gregor.Dir; Simon Schneider. Real Life Documentary, Canada 2014.",
                "pageType": "",
            },
        ],
    },
}


export const getDeleteIconClassname = (props) => {
    let {isEditMode, selectedNotifications} = props;
    if (isEditMode && !selectedNotifications.length) {
        return 'icon-trash-grey edit-mode disable'
    } else if (isEditMode) {
        return 'icon-trash-grey'
    } else {
        return 'icon-trash-grey'
    }
}